# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scarlet}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joao Carlos Cardoso"]
  s.date = %q{2010-05-17}
  s.default_executable = %q{scarlet}
  s.description = %q{Generates XHTML slideshows from text files using Textile for markup. Does syntax highlighting if Pygments is installed.}
  s.email = %q{mail@joao-carlos.com}
  s.executables = ["scarlet"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "bin/scarlet",
     "lib/scarlet.rb",
     "lib/scarlet/formatter.rb",
     "lib/scarlet/formatters/base.rb",
     "lib/scarlet/formatters/html.rb",
     "lib/scarlet/formatters/latex.rb",
     "lib/scarlet/formatters/pdf.rb",
     "lib/scarlet/generator.rb",
     "lib/scarlet/highlighter.rb",
     "lib/scarlet/runner.rb",
     "lib/scarlet/slide.rb",
     "lib/scarlet/slideshow.rb",
     "lib/scarlet/templates/html/default.erb",
     "lib/scarlet/templates/html/javascripts/jquery.easing.js",
     "lib/scarlet/templates/html/javascripts/jquery.hash-changed.js",
     "lib/scarlet/templates/html/javascripts/jquery.min.js",
     "lib/scarlet/templates/html/javascripts/slides.js",
     "lib/scarlet/templates/html/stylesheets/slides.css",
     "lib/scarlet/templates/html/stylesheets/syntax_colorful.css",
     "lib/scarlet/templates/html/stylesheets/syntax_default.css",
     "lib/scarlet/templates/html/stylesheets/syntax_emacs.css",
     "lib/scarlet/templates/html/stylesheets/syntax_friendly.css",
     "lib/scarlet/templates/latex/default.erb"
  ]
  s.homepage = %q{http://github.com/jcxplorer/scarlet}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{scarlet}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Slideshow Generator with Textile}
  s.test_files = [
    "spec/scarlet/slide.rb",
     "spec/scarlet/slideshow.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<open4>, [">= 0.9.6"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 4.2.2"])
      s.add_runtime_dependency(%q<rtex>, [">= 2.1.1"])
    else
      s.add_dependency(%q<open4>, [">= 0.9.6"])
      s.add_dependency(%q<RedCloth>, [">= 4.2.2"])
      s.add_dependency(%q<rtex>, [">= 2.1.1"])
    end
  else
    s.add_dependency(%q<open4>, [">= 0.9.6"])
    s.add_dependency(%q<RedCloth>, [">= 4.2.2"])
    s.add_dependency(%q<rtex>, [">= 2.1.1"])
  end
end

